<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>MWDA-Control</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Mwda.Control.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Mwda.Control.ico" />
  </ItemGroup>

</Project>
